#!/bin/bash
LATEST_VERSION="5.0.1-SNAPSHOT"
#If we are building from master, tag as latest
if [ "$DOCKER_TAG" = "$LATEST_VERSION" ]; then
    docker tag $IMAGE_NAME $DOCKER_REPO:latest
    docker push $DOCKER_REPO:latest
fi