#!/usr/bin/env bash
unset OIDC_AUTH_LOCATION
unset OIDC_TOKEN_LOCATION
unset OIDC_CLIENT_ID
unset OIDC_REDIRECT_BASE_URL
unset KIE_SERVER_BASE_URL
unset KIE_SERVER_USERNAME
unset KIE_SERVER_PASSWORD
unset DEPLOY_POSTGRESQL
unset DB_SERVICE_HOST
unset DB_SERVICE_PORT
unset DB_USERNAME
unset DB_PASSWORD
unset DB_ADMIN_USERNAME
unset DB_ADMIN_PASSWORD
unset PORT_DB_NAME
unset SERV_DB_NAME

